//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirebaseNet.Tests.Serialization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SerializedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SerializedMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirebaseNet.Tests.Serialization.SerializedMessages", typeof(SerializedMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to { &quot;multicast_id&quot;: 216,
        ///  &quot;success&quot;: 3,
        ///  &quot;failure&quot;: 3,
        ///  &quot;canonical_ids&quot;: 1,
        ///  &quot;results&quot;: [
        ///    { &quot;message_id&quot;: &quot;1:0408&quot; },
        ///    { &quot;error&quot;: &quot;Unavailable&quot; },
        ///    { &quot;error&quot;: &quot;InvalidRegistration&quot; },
        ///    { &quot;message_id&quot;: &quot;1:1516&quot; },
        ///    { &quot;message_id&quot;: &quot;1:2342&quot;, &quot;registration_id&quot;: &quot;32&quot; },
        ///    { &quot;error&quot;: &quot;NotRegistered&quot;}
        ///  ]
        ///}.
        /// </summary>
        public static string DownstreamMessageResponseJSON {
            get {
                return ResourceManager.GetString("DownstreamMessageResponseJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {
        ///  &quot;to&quot;: &quot;bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...&quot;,
        ///  &quot;notification&quot;: {
        ///    &quot;title&quot;: &quot;Portugal vs. Denmark&quot;,
        ///    &quot;body&quot;: &quot;great match!&quot;,
        ///    &quot;icon&quot;: &quot;myicon&quot;
        ///  }
        ///}.
        /// </summary>
        public static string SimpleMessageJSON {
            get {
                return ResourceManager.GetString("SimpleMessageJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;message_id&quot;:-1}.
        /// </summary>
        public static string TopicMessageResponseJSON {
            get {
                return ResourceManager.GetString("TopicMessageResponseJSON", resourceCulture);
            }
        }
    }
}
